/**
 * Action Types 常量
 * @type {{}}
 */

export const BASE = {
  SHOW_LOADING: 'SHOW_LOADING',
  SET_CURR_LOCATION: 'SET_CURR_LOCATION',
  SET_CURR_HOSPITAL: 'SET_CURR_HOSPITAL',
  SET_CURR_AREA: 'SET_CURR_AREA',
  // 屏幕尺寸，根据屏幕旋转自动变动
  SET_SCREEN: 'SET_SCREEN',
  // Tab内工作区高度
  SET_WSHEIGHT: 'SET_WSHEIGHT',
  // 屏幕方向
  SET_ORIENTATION: 'SET_ORIENTATION',
  // 待办列表
  SET_TODOS: 'SET_TODOS',
  // 病区及当前病区
  SET_INPATIENT_AREAS: 'SET_INPATIENT_AREAS',
  SET_CURR_INPATIENT_AREA: 'SET_CURR_INPATIENT_AREA',
  // 所有患者及当前患者
  SET_PATIENTS: 'SET_PATIENTS',
  SET_CURR_PATIENT: 'SET_CURR_PATIENT',
  RESET_BACK_NAVIGATE: 'RESET_BACK_NAVIGATE',
};

export const AUTH = {
  GOTO_LOGIN: 'GOTO_LOGIN',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  UPDATE_USER: 'UPDATE_USER',
};
