DROP TABLE IF EXISTS IH_EBPP_BILLCATALOG;

DROP TABLE IF EXISTS IH_EBPP_BILLINSTANCE;

DROP TABLE IF EXISTS IH_EBPP_BILLINSTANCELOG;

DROP TABLE IF EXISTS IH_EBPP_BILLPAYINFO;

DROP TABLE IF EXISTS IH_EBPP_BILLTYPE;

DROP TABLE IF EXISTS IH_EBPP_BIZCHANNEL;

DROP TABLE IF EXISTS IH_EBPP_PAYCHANNEL;

DROP TABLE IF EXISTS IH_EBPP_PAYINFO;

CREATE TABLE IH_EBPP_BILLCATALOG
(
   CODE                 CHAR(32) NOT NULL,
   NAME                 VARCHAR(100),
   MEMO                 VARCHAR(100),
   CREATED_ON           VARCHAR(19),
   STATUS               CHAR(2) COMMENT '01-启用
            02-暂时停用
            00-作废',
   PARENT_ID            CHAR(32),
   PRIMARY KEY (CODE)
);

ALTER TABLE IH_EBPP_BILLCATALOG COMMENT '--公共事业缴费
---------教育类
---------生活类

';

CREATE TABLE IH_EBPP_BILLINSTANCE
(
   ID                   CHAR(32) NOT NULL,
   NO                   VARCHAR(30),
   _TYPE                CHAR(32),
   FLAG                 CHAR(1) COMMENT '1-可用
            0-撤销',
   STATUS               CHAR(1) COMMENT '01-新建
            08-异常关闭
            09-正常关闭
            11-支付中
            12-支付成功
            21-支付异常
            22-支付失败
            ',
   CREATED_ON           CHAR(19),
   UPDATED_ON           CHAR(19),
   FINISHED_ON          CHAR(19),
   MEMO                 VARCHAR(255),
   CCY                  CHAR(3),
   AMT                  NUMERIC(17,2) DEFAULT 0,
   BIZCH_CODE           CHAR(6),
   ORIBIZNO             VARCHAR(50),
   PAYER_ACCT           VARCHAR(50),
   PAYER_CODE           VARCHAR(50),
   PAYER_NAME           VARCHAR(70),
   PAYEE_ACCT           VARCHAR(50),
   PAYEE_CODE           VARCHAR(50),
   PAYEE_NAME           VARCHAR(70),
   TRANS_ON             CHAR(19) COMMENT '业务原始生成时间，由调用方发送',
   EXTRA1               VARCHAR(100),
   EXTRA2               VARCHAR(100),
   EXTRA3               VARCHAR(100),
   EXTRA4               VARCHAR(100),
   EXTRA5               VARCHAR(100),
   EXTRA6               VARCHAR(100),
   EXTRA7               VARCHAR(100),
   EXTRA8               VARCHAR(100),
   EXTRA9               VARCHAR(100),
   EXTRA10              VARCHAR(100),
   PRIMARY KEY (ID)
);

CREATE TABLE IH_EBPP_BILLINSTANCELOG
(
   ID                   CHAR(32) NOT NULL,
   BILL_ID              CHAR(32),
   OPERATE_ON           VARCHAR(19),
   CONTENT              TEXT,
   ORI_DATA             TEXT,
   PRE_DATA             TEXT,
   PRIMARY KEY (ID)
);

CREATE TABLE IH_EBPP_BILLPAYINFO
(
   B_ID                 CHAR(32) NOT NULL,
   P_ID                 CHAR(32) NOT NULL,
   PRIMARY KEY (B_ID, P_ID)
);

CREATE TABLE IH_EBPP_BILLTYPE
(
   CODE                 CHAR(32) NOT NULL,
   NAME                 VARCHAR(100),
   MEMO                 VARCHAR(100),
   BIZCH_CODE           CHAR(6) COMMENT '类型 0-特色业务费种 1-外部业务费种 2-开放费种',
   CREATED_ON           VARCHAR(19),
   STATUS               CHAR(2) COMMENT '01-启用
            02-暂时停用
            00-作废
            ',
   CATLOG_ID            CHAR(32),
   PRIMARY KEY (CODE)
);

ALTER TABLE IH_EBPP_BILLTYPE COMMENT '--物业费
--学费
--供暖费
--水费
--电费
--燃';

CREATE TABLE IH_EBPP_BIZCHANNEL
(
   CODE                 CHAR(6) NOT NULL,
   NAME                 VARCHAR(100),
   _TYPE                CHAR(2) COMMENT '01-直接业务渠道
            02-代理业务渠道',
   STATUS               CHAR(2) COMMENT '01-启用
            00-作废
            02-暂时停用',
   MEMO                 VARCHAR(100),
   CREATED_ON           VARCHAR(19),
   PRIMARY KEY (CODE)
);

CREATE TABLE IH_EBPP_PAYCHANNEL
(
   CODE                 CHAR(6) NOT NULL,
   NAME                 VARCHAR(100),
   MEMO                 VARCHAR(100),
   STATUS               CHAR(2) COMMENT '01-启用
            00-作废
            02-暂时停用
            ',
   CREATED_ON           VARCHAR(19),
   BIZCH_CODE           CHAR(6),
   PRIMARY KEY (CODE)
);

CREATE TABLE IH_EBPP_PAYINFO
(
   ID                   CHAR(32) NOT NULL,
   SEQUENCENO           VARCHAR(30),
   STATUS               CHAR(2),
   AMT                  NUMERIC(17,2),
   TRAN_TIEM            VARCHAR(19),
   TRAN_WAY             CHAR(2) COMMENT '--01-积分
            --02-优惠券
            --03-余额支付
            --04-红包',
   TRAN_QUANTITY        CHAR(6),
   TRAN_CHANEL          CHAR(6),
   EXTRA1               VARCHAR(100),
   EXTRA2               VARCHAR(100),
   EXTRA3               VARCHAR(100),
   EXTRA4               VARCHAR(100),
   EXTRA5               VARCHAR(100),
   EXTRA6               VARCHAR(100),
   EXTRA7               VARCHAR(100),
   EXTRA8               VARCHAR(100),
   EXTRA9               VARCHAR(100),
   EXTRA10              VARCHAR(100),
   PRIMARY KEY (ID)
);

ALTER TABLE IH_EBPP_BILLCATALOG ADD CONSTRAINT FK_BILLCATALOG_PARENT FOREIGN KEY (PARENT_ID)
      REFERENCES IH_EBPP_BILLCATALOG (CODE) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE IH_EBPP_BILLINSTANCE ADD CONSTRAINT FK_BILLINSTANCE_BIZCH_CODE FOREIGN KEY (BIZCH_CODE)
      REFERENCES IH_EBPP_BIZCHANNEL (CODE) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE IH_EBPP_BILLINSTANCE ADD CONSTRAINT FK_FK_BILLINSTANCE_TYPE FOREIGN KEY (_TYPE)
      REFERENCES IH_EBPP_BILLTYPE (CODE) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE IH_EBPP_BILLINSTANCELOG ADD CONSTRAINT FK_BILLINSTANCELOG_BILL_ID FOREIGN KEY (BILL_ID)
      REFERENCES IH_EBPP_BILLINSTANCE (ID) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE IH_EBPP_BILLPAYINFO ADD CONSTRAINT FK_BILLPAYINFO_B_ID FOREIGN KEY (B_ID)
      REFERENCES IH_EBPP_BILLINSTANCE (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE IH_EBPP_BILLPAYINFO ADD CONSTRAINT FK_BILLPAYINFO_P_ID FOREIGN KEY (P_ID)
      REFERENCES IH_EBPP_PAYINFO (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE IH_EBPP_BILLTYPE ADD CONSTRAINT FK_BILLTYPE_BIZCH_CODE FOREIGN KEY (BIZCH_CODE)
      REFERENCES IH_EBPP_BIZCHANNEL (CODE) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE IH_EBPP_BILLTYPE ADD CONSTRAINT FK_BILLTYPE_CATALOIOG_ID FOREIGN KEY (CATLOG_ID)
      REFERENCES IH_EBPP_BILLCATALOG (CODE) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE IH_EBPP_PAYCHANNEL ADD CONSTRAINT FK_PAYCHANNEL_BIZCH_CODE FOREIGN KEY (BIZCH_CODE)
      REFERENCES IH_EBPP_BIZCHANNEL (CODE) ON DELETE SET NULL ON UPDATE CASCADE;

