#%RAML 0.8
title: hospital_REST_API
version: 1.0
baseUri: http://server/api/{version}
/{id}:
  get:                  
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": ""
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                 "name": {
                    "type": "string"
                  }
                }
              }
/doctor/list:
  get:                  
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": ""
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                 "name": {
                    "type": "string"
                  }
                }
              }
/department/list:
  get:                  
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": ""
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                 "name": {
                    "type": "string"
                  }
                }
              }