#%RAML 0.8
title: inpatient_REST_API
version: 1.0
baseUri: http://server/api/{version}
/{patientId}:
  get:                  
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": ""
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                 "name": {
                    "type": "string"
                  }
                }
              }
/dailyBill/list:
  get:                  
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": ""
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                 "name": {
                    "type": "string"
                  }
                }
              }
/inpatientBill/list:
  get:                  
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": ""
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                 "name": {
                    "type": "string"
                  }
                }
              }
/inpatientBill/list/items:
  get:                  
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": ""
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                 "name": {
                    "type": "string"
                  }
                }
              }
/deposit/balance:
  get:                  
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": ""
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  },
                 "name": {
                    "type": "string"
                  }
                }
              }
/deposit/book:
  post:
    body:
      application/json:
        example: |
          {
              "id":""
          }
        schema: |
          {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              }
            }
          }  
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "id":""
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string"
                  }
                }
              }
   

