/**
 * Action Types 常量
 * @type {{}}
 */

export const BASE = {
  CHANGE_TAB_TITLE: 'CHANGE_TAB_TITLE',
  SHOW_LOADING: 'SHOW_LOADING',
  SET_CURR_LOCATION: 'SET_CURR_LOCATION',
  SET_CURR_PATIENT: 'SET_CURR_PATIENT',
  SET_CURR_HOSPITAL: 'SET_CURR_HOSPITAL',
  SET_CURR_AREA: 'SET_CURR_AREA',
  RESET_BACK_NAVIGATE: 'RESET_BACK_NAVIGATE',
  RESET_WHEN_LOGOUT: 'RESET_WHEN_LOGOUT',
  SWITCH_EDITION: 'SWITCH_EDITION',
};

export const AUTH = {
  GOTO_LOGIN: 'GOTO_LOGIN',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  UPDATE_USER: 'UPDATE_USER',
};
