platform :ios, '8.0'

target 'MSH' do
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/', :subspecs => [
    'BatchedBridge',
  ]
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end